project:
  type: website

website:
  title: "FB2NEP Nutritional Epidemiology"
  site-url: https://ggkuhnle.github.io/fb2nep-epi/
  repo-url: https://github.com/ggkuhnle/fb2nep-epi
  repo-actions: [issue, source]
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: notebooks/index.qmd
        text: Notebooks
      - href: metadata/provenance.md
        text: Provenance
      - href: assessment/A1_brief.md
        text: Assessment 1
  sidebar:
    style: floating
    search: true
    contents:
      - index.qmd
      - section: "Notebooks"
        # Lists all .ipynb in notebooks/ in alphanumeric order
        contents:
          - notebooks/index.qmd
          - notebooks/*.ipynb
      - section: "Slides (PDF)"
        # Links directly to PDFs in slides/
        contents:
          - slides/*.pdf

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    number-sections: true
    code-tools: true
    smooth-scroll: true
  # ensure PDFs are copied verbatim
  pdf: default

# Don’t execute notebooks during render (fast, deterministic HTML)
execute:
  eval: false

# Copy these assets straight through to the site
resources:
  - slides/**
  - data/**
  - metadata/**
  - assessment/**

# Nice footer with licence and build info
website:
  page-footer:
    left: "© University of Reading 2025 · Licensed <a href='https://creativecommons.org/licenses/by/4.0/'>CC BY 4.0</a>"
    right: "Built with Quarto"
