name: CI

on: [push, pull_request]

jobs:
  build-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt scipy
      - run: python scripts/generate_dataset.py
      - run: python scripts/validate_dataset.py

