name: Build HTML and Deploy Pages

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt nbconvert jupyter
      - name: Convert notebooks to HTML
        run: |
          rm -rf docs
          mkdir -p docs
          jupyter nbconvert --to html --output-dir docs notebooks/*.ipynb
          # simple index
          python - <<'PY'
          import glob, os
          items = []
          for p in sorted(glob.glob("docs/*.html")):
            n = os.path.basename(p)
            items.append(f'<li><a href="{n}">{n}</a></li>')
          html = "<h2>FB2NEP Notebooks (HTML)</h2><ul>" + "".join(items) + "</ul>"
          open("docs/index.html","w").write(html)
          PY
      - name: Commit docs (optional cache-in-repo)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs
          git commit -m "Update HTML docs" || echo "No changes"
          git push
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: docs
      - uses: actions/deploy-pages@v4

