name: Quarto Publish

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install Quarto CLI
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: "latest"

      # Python is needed to render .ipynb
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Jupyter engine (no execution)
        run: |
          python -m pip install --upgrade pip
          pip install jupyter

      # Render the Quarto site (assumes you have _quarto.yml at repo root)
      - name: Render site
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: .
          # omit 'to:' to use defaults from _quarto.yml
          # rendering does NOT execute notebooks unless you set execute: true in _quarto.yml

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

